### ISSUE TITLE
1.8. Log-in järel näidatakse soovitud lehte

### ISSUE THREAD

**Issue by koodid** [koodid/kidsa#8]

**Comment by ProditorMagnus** [comment]
Kui login olmas oleks saaks juba teha https://github.com/koodid/kidsa/commit/6e1f39b538031362c259ab6635aa0a284eeafb29#diff-fedd9058390add02c421a7038d2c877fR9

**Comment by ProditorMagnus** [comment]
ab6efdc860b81708c4ddc49eab447f4976299967 b3537465652e61911a2167d1b9cc339d2eb98e4d
